FROM node:20
WORKDIR /demo/frontend
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
ENV PORT 4000
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL ${NEXT_PUBLIC_API_URL}
RUN yarn build

EXPOSE 4000
CMD ["yarn", "start"]
