FROM nginx:latest

COPY default.conf /etc/nginx/conf.d/default.conf

# COPY default_https.conf /etc/nginx/conf.d/default.conf


# COPY private.key /etc/ssl/private/private.key
# COPY certificate.pem /etc/ssl/certs/certificate.pem